# Project: MidToSuffixProject
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o midtosuffixclass.o
LINKOBJ  = main.o midtosuffixclass.o
LIBS     = -L"D:/programs/Dev_Cpp/MinGW64/lib" -L"D:/programs/Dev_Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/programs/Dev_Cpp/MinGW64/include" -I"D:/programs/Dev_Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/programs/Dev_Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/programs/Dev_Cpp/MinGW64/include" -I"D:/programs/Dev_Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/programs/Dev_Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/programs/Dev_Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = MidToSuffixProject.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

midtosuffixclass.o: midtosuffixclass.cpp
	$(CPP) -c midtosuffixclass.cpp -o midtosuffixclass.o $(CXXFLAGS)
